f=open("test.txt")#open mode
f=open("test.txt",'r')
content=f.read()
print(content)
f=open("test.txt",'w')
f.write("file handling learning")
f.close()
f=open("test.txt",'a')
x=f.write("\nby vijaya bala")
print(x)
f.close()
f=open('test.txt','r')
y=len(f.read())
print(y)
